#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder


# In[2]:


iris = datasets.load_iris(as_frame=True).frame


# In[3]:


iris = pd.read_csv("iris.csv")


# In[4]:


import seaborn as sns
counts = iris["variety"].value_counts()
sns.barplot(data = counts)


# In[5]:


iris = pd.read_csv("iris.csv")


# In[6]:


iris


# In[7]:


iris.info()


# In[8]:


iris[iris.duplicated(keep= False)]


# In[9]:


labelencoder = LabelEncoder()
iris.iloc[:,-1] = labelencoder.fit_transform(iris.iloc[:,-1])
iris.head()


# In[10]:


iris.info()


# # Observation
# ~the target column is still object type.it needs to be converted to numeric}

# In[11]:


iris['variety'] = pd.to_numeric(labelencoder.fit_transform(iris['variety']))
print(iris.info())


# In[12]:


X=iris.iloc[:,0:4]
Y=iris['variety']

Y
# In[14]:


x_train, x_test,y_train,y_test = train_test_split(X,Y, test_size=0.3,random_state = 1)
x_train


# Decision Tree

# In[15]:


model =DecisionTreeClassifier(criterion = 'entropy', max_depth=None)
model.fit(x_train,y_train)


# In[19]:


plt.figure(dpi=1200)
tree.plot_tree(model);


# In[ ]:




